[build-system]
requires = ["scikit-build-core", "pybind11", "setuptools-git-versioning"]
build-backend = "scikit_build_core.build"

[tool.setuptools-git-versioning]
template = "{tag}"
dev_template = "{tag}.post{ccount}+git.{sha}"
dirty_template = "{tag}.post{ccount}+git.{sha}.dirty"

[project]
name = "cholsky_update"
dynamic = ["version"]
authors = [
  { name="Chris MacLellan", email="cmaclell@gatech.edu" },
]
description = "Wrapper around eigen's cholsky operations for numpy arrays"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
]

[project.urls]
Homepage = "https://github.com/cmaclell/cholsky_update"

